name: pub_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.6.0

isar_version: &isar_version 3.0.2 # define the version to be used

dependencies:
  auto_size_text: ^3.0.0
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  copy_with_extension: ^6.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  isar:
    path: ../../packages/isar
  isar_flutter_libs:
    path: ../../packages/isar_flutter_libs
  json_annotation: ^4.9.0
  markdown: ^6.0.0
  pub_semver: ^2.1.1
  pubspec: ^2.3.0
  pubspec_parse: ^1.4.0
  riverpod: ^2.6.1
  shimmer: ^2.0.0
  tar: ^0.5.6
  timeago: 3.7.0
  url_launcher: ^6.3.1
  go_router: ^14.6.2
  path_provider: ^2.1.5
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0-alpha.6
  flutter_html_svg: ^3.0.0-alpha.4

dev_dependencies:
  build_runner: ^2.4.14
#  copy_with_extension_gen: ^6.0.0
  isar_generator:
    path: ../../packages/isar_generator
  json_serializable: ^6.9.2
  flutter_lints: ^5.0.0
dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/ff_banner.png
    - assets/pub_logo.svg
    - assets/pub_logo_dark.svg
    - assets/search_bg.svg
