name: isar_test

publish_to: "none"

version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.17.1
  copy_with_extension: ^6.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  integration_test:
    sdk: flutter
  intl: 0.18.1
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  test: any

dev_dependencies:
  build_runner: any
  copy_with_extension_gen: ^6.0.0`
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0

#dependency_overrides:
#  isar:
#    path: ../isar
#  isar_flutter_libs:
#    path: ../isar_flutter_libs
