name: isar_test

publish_to: "none"

version: 1.0.0+1

resolution: workspace 
environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl: 0.19.0
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  json_annotation: ^4.9.0
  meta: ^1.15.0
  path: ^1.9.0
  path_provider:
  test: ^1.21.4
  test_api: ^0.7.3

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: any
  json_serializable: ^6.9.2
  very_good_analysis: ^7.0.0
