name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^7.1.0
  build: ^2.4.2
  dart_style: ^3.0.1
  dartx: ^1.2.0
  glob: ^2.1.2
  isar:
    path: ../isar
  path: ^1.9.0
  source_gen: ^2.0.0
  xxh3: ^1.2.0

dev_dependencies:
  build_test: ^2.1.5
  matcher: ^0.12.12
  test: ^1.21.1
  very_good_analysis: ^7.0.0

dependency_overrides:
  source_gen: ^2.0.0
  analyzer: ^7.1.0
  dart_style: ^3.0.1