name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  isar:
    path: ../isar
  vm_service: 14.3.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  very_good_analysis: ^7.0.0

dependency_overrides:
  source_gen: ^2.0.0
  analyzer: ^7.1.0
  dart_style: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
