name: isar_inspector
publish_to: "none"
version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  isar:
    path: ../isar
  vm_service: 14.3.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
